### ISSUE TITLE
error when updating coffee_rails to 3.2.0 in rubygems 1.3.7

### ISSUE THREAD

**Issue by thoughtafter** [rails/coffee-rails#19]
sudo gem1.9.1 update --no-ri --no-rdoc
Updating installed gems
Updating coffee-rails
ERROR:  While executing gem ... (NoMethodError)
    undefined method `call' for nil:NilClass
